### PR TITLE
Fix bug where dropdown menu does not work on iOS devices

### LINKED ISSUE #1394: Dropdown does not work in mobile
Basically the dropdown menu on the navbar does not work for mobile devices. To reproduce, use a mobile phone, go to navbar, from the dropdown list, try to open 'My Courses'. Button does not get triggered. 

I read about a boostrap fix but need to double check before we fix it -> https://github.com/twbs/bootstrap/issues/7968 

On iPhone 6, tried on Chrome and Safari. Bug was existent in both.

### PR DESCRIPTION
**Pull request by weiqingtoh**
Fixes #1394. 

The dropdown doesn't work for iOS devices. After some reading, it seems like iOS doesn't support clicks event delegation (it doesn't recognise clicks on certain HTML elements) if it is an input or link. Because of that, tapping on the dropdown trigger doesn't trigger a 'click', but rather a 'touch'.

This PR fixes that by adding the event listeners for the elements that are declared to be `dropdown` (according to bootstrap's dropdown.js). Will need your guys help to see if I've wrote the javascript properly, as I don't write that much javascript >_<

According to the article below, apparently there is a slim chance that if a page has too many dropdowns, it is possible that there will be 'memory management' issues. In my testing with iPhone (and other android devices), I did not experience any significant difference before and after this fix. 

Readings:
 - More about event delegation on iOS:
  - [Article 1](http://www.quirksmode.org/blog/archives/2010/09/click_event_del.html)
  - [Article 2](http://www.shdon.com/blog/2013/06/07/why-your-click-events-don-t-work-on-mobile-safari)
 - Proposed [fix on StackOverflow](http://stackoverflow.com/a/22318440)

From Article 2:
>By virtue of event bubbling, the parent (<body> in the jQuery example) catches all child elements `(<div class="clickable">)` being clicked. Such a construct enables you have only 1 click handler for any number of matching elements without needing to bind them to each element individually. This works on every standards-compliant browser. Mobile Safari chooses to differ, however. It does not generate click events for elements that do not have either or both of:
> - A directly bound onclick handler.
> - The cursor property set to pointer in CSS.

### CODE REVIEW

File: app/assets/javascripts/layout.js [hunk 1]
```diff
@@ -13,15 +13,23 @@
     $('textarea.text', element).summernote();
   }
 
+  // Dropdown does not work on iOS devices as they only support click delegation for
+  // Proposed solution is modified from http://stackoverflow.com/a/22318440
+  // Event delegation for iOS http://www.quirksmode.org/blog/archives/2010/09/click_event_del.html
+  function initializeDropdownEventListener(element) {
```
Comment (weiqingtoh) [inline app/assets/javascripts/layout.js]: Fixed

File: app/assets/javascripts/layout.js [hunk 2]
```diff
@@ -13,15 +13,23 @@
...
     $('[data-toggle="popover"]', element).popover();
-    // The design of Coursemology is such that tooltips are attached to any
-    // element with a title attribute, but we do not want that for the Facebook
-    // button
+    // Tooltips are attached to elements with a title attribute, except for the Facebook button.
     // See https://github.com/Coursemology/coursemology-theme/pull/5
     $('[title]', element).not('.fb-like *').tooltip();
     $('input.toggle-all[type="checkbox"]', element).checkboxToggleAll();
     $('textarea.code', element).ace();
+    initializeDropdownEventListener();
```
Comment (allenwq) [inline app/assets/javascripts/layout.js]: The `initializeComponents` is called after every DOM insertion, do you really need it here ?

Comment (weiqingtoh) [inline app/assets/javascripts/layout.js]: I will only really need it if 2 conditions are met: 
 - There are dropdown menus in that page (which is almost every page because of the navbar)
 - If it is loaded on an iOS device.

Should I find another way to do this @allenwq ?

Comment (weiqingtoh) [inline app/assets/javascripts/layout.js]: Ok misread, don't think we need on every Dom insertion, but rather on every page load.

Comment (allenwq) [inline app/assets/javascripts/layout.js]: Then on turbolinks:load would be enough. Just bind to that event.

Comment (weiqingtoh) [inline app/assets/javascripts/layout.js]: Fixed!
