### PR TITLE
Topics: Fix 403 when accessing user profile from Comments

### LINKED ISSUE #4990: Comments hyperlink to user links incorrectly references userId instead of courseUserId
1. Hyperlinks on names are linking to `user.id` instead of `courseUser.id`

https://coursemology.org/courses/course-id/comments

https://github.com/Coursemology/coursemology2/blob/5cc2d482fa917b8122a1f88bcd38553e1b6278d5/client/app/bundles/course/discussion/topics/components/cards/CommentCard.tsx#L205

2. Seperately, the avatar should be linked as well, users will expect to be able to click on the image to link to user.  
See how leaderboard does this:

https://github.com/Coursemology/coursemology2/blob/6a48de998559ec2a4c42140646747120b5838525/client/app/bundles/course/leaderboard/components/tables/LeaderboardTable.tsx#L137

~~3. For consistency, comments and annotations in the submission page should also be hyperlinked
https://coursemology.org/courses/course-id/assessments/assessment-id/submissions/submission-id/edit~~

### PR DESCRIPTION
**Pull request by purfectliterature**
Closes #4990.

* Add user profile hyperlink to user's avatar in Comments
* `/courses/:course_id/comments/all` and `/courses/:course_id/comments/pending` now returns JSON with an additional `userUrl` field with the following behaviour:
  * If the `creator` is in the course, i.e., has/is a `CourseUser`, `id` is the course user ID, and `userUrl` is the course user URL.
  * If the `creator` is not in the course, `id` is the user ID, and `userUrl` is the user URL.

### CODE REVIEW

File: app/helpers/course/controller_helper.rb [hunk 1]
```diff
@@ -30,6 +30,16 @@ def display_user(user)
     end
   end
 
+  # URL to the profile page of the given +CourseUser+ in the current course
+  #
+  # @param [CourseUser] course_user The +CourseUser+ to link to
+  # @return [String] A URL that points to the +CourseUser+ profile page
+  def url_to_course_user(course_user)
```
Comment (ekowidianto) [inline app/helpers/course/controller_helper.rb:37]: I dont think you need to have this helper at all since we know that `course_user` is `CourseUser`, and the link can just be generated by calling `course_user_path` directly

File: app/helpers/course/users_helper.rb [hunk 2]
```diff
@@ -1,4 +1,24 @@
 # frozen_string_literal: true
 module Course::UsersHelper
-  include Course::Achievement::AchievementsHelper
+  # Returns a hash that maps +User+ ids to their +CourseUser+ IDs in a given +course_id+
+  #
+  # @param [Integer] course_id The ID of the course
+  # @return [Hash]
+  def preload_course_user_ids_hash(course_id)
```
Comment (ekowidianto) [inline app/helpers/course/users_helper.rb:7]: This function is not used anywhere right?

File: app/helpers/course/users_helper.rb [hunk 3]
```diff
@@ -1,4 +1,24 @@
...
+    course_users_in(course_id).to_h { |course_user| [course_user.user_id, course_user.id] }
+  end
+
+  # Returns a hash that maps +User+ ids to their +CourseUser+ in a given +course_id+
+  #
+  # @param [Integer] course_id The ID of the course
+  # @return [Hash]
+  def preload_course_users_hash(course_id)
```
Comment (ekowidianto) [inline app/helpers/course/users_helper.rb:15]: I think you can pass in `course` instead of `course_id` and then you can load the course users by association (eg `course.course_users`

File: app/helpers/course/controller_helper.rb (hunk 1 above)
Comment (ekowidianto) [reply app/helpers/course/controller_helper.rb:37]: Perhaps, you can also pass `user` to this function. Check if course_user if nil. If it is nil, then return user_path instead. Call this something like `url_to_course_user_or_user`

File: app/controllers/course/discussion/topics_controller.rb [hunk 4]
```diff
@@ -108,4 +104,14 @@ def component
   def mark_as_pending?
     params[:pending] == 'true'
   end
+
+  def render_topics_list_data
+    @topic_count = @topics.count
+    @topics = @topics.paginated(pagination_page_param)
+
+    course_id = @current_course_user&.course_id
```
Comment (ekowidianto) [inline app/controllers/course/discussion/topics_controller.rb:112]: you can use `current_course` instead

**Review by ekowidianto — CHANGES_REQUESTED** [review]
Thanks @purfectliterature ! some nit comments below

File: app/helpers/course/users_helper.rb (hunk 2 above)
Comment (purfectliterature) [reply app/helpers/course/users_helper.rb:7]: Not that I know of. I left it there in case someone needs it, but I guess when that time comes, they can write the same function here again. I will remove it.

File: app/helpers/course/controller_helper.rb (hunk 1 above)
Comment (ekowidianto) [reply app/helpers/course/controller_helper.rb:37]: Also pass `course` to this function to ensure that there is no additional query to get the course

**Review by ekowidianto — APPROVED** [review]
