### PR TITLE
Add new line to comment section to fix alignment issue

### LINKED ISSUE #4530: Annotation line display is offset to an incorrect position
image
User commented here on line 227

image
But the 227 seems to be aligned to the wrong line of code here.

Possibly related to #4153 Fix misalignment between code line number and code line, and the recent MUI upgrade

### PR DESCRIPTION
**Pull request by leeroy999**
Fixes #4530

New line is added to Comment section as follows:
image

This is to fix the pre-existing alignment issue which is caused by <div> tags wrapping around the code, resulting in the lines being pushed down by one line:

image

This fix is used to prevent shifting of old comments to the wrong lines. Trimming the first and last line would cause the old comments to be at the wrong lines.

### CODE REVIEW

File: app/helpers/course/discussion/topics_helper.rb [hunk 1]
```diff
@@ -15,7 +15,8 @@ def topics_title
   # @param [Integer] line_end The one based end line line number.
   # @return [String] A HTML fragment containing the code lines.
   def display_code_lines(file, line_start, line_end)
-    code = file.lines((line_start - 1)..(line_end - 1)).join("\n")
+    code = file.add_line.lines((line_start - 1)..(line_end - 1)).join("\n")
```
Comment (ekowidianto) [inline app/helpers/course/discussion/topics_helper.rb:18]: Could you add a comment above this line on why a line is added?

**Review by ekowidianto — APPROVED** [review]
Thanks! LGTM and see minor comment

File: app/helpers/course/discussion/topics_helper.rb (hunk 1 above)
Comment (leeroy999) [reply app/helpers/course/discussion/topics_helper.rb:19]: Ok done!
