### PR TITLE
Mark test cases as failed if student code cannot be evaluated.

### LINKED ISSUE #1236: Show stdout/stderr when autograded student code has syntax errors
The programming import service checks for errors and returns the stdout and stderr if there are any.

The programming auto grading service should do the same thing. Right now it goes through the workflow with a nil test report, so the student doesn't see anything happening.

### PR DESCRIPTION
**Pull request by fonglh**
This is most likely due to a syntax error in the student's submission.

Fixes #1236

### CODE REVIEW

File: app/services/course/assessment/answer/programming_auto_grading_service.rb [hunk 1]
```diff
@@ -88,6 +92,14 @@ def build_test_case_records(question, auto_grading, test_report)
     end
   end
 
+  def build_failed_test_case_records(question, auto_grading)
+    question.test_cases.map do |test_case|
+      auto_grading.test_results.build(auto_grading: auto_grading, test_case: test_case,
+                                      passed: false,
+                                      message: 'Evaluation failed. Syntax error?')
```
Comment (allenwq) [inline app/services/course/assessment/answer/programming_auto_grading_service.rb]: This need to be translated.
