### PR TITLE
Coursemology/coursemology2#2875 video duplication

### LINKED ISSUE #2875: Duplication of Videos do not work as expected
There is no corresponding tab "default" tab in the target course.
Creation of new tabs through the video page or the course settings page does not work.

@yichenshen can help to fix?

### PR DESCRIPTION
**Pull request by yichenshen**
Fixes #2875. 

Previously video tabs are not cloned, So videos get tagged to the tabs in the old course.

The last commit includes a migration to remove any potential videos that were cloned wrongly. These videos would not have showed up in the UI in any case.

### CODE REVIEW

File: app/models/course/video/tab.rb [hunk 1]
```diff
@@ -24,6 +24,10 @@ def other_tabs_remaining?
     course.video_tabs.count > 1
   end
 
+  def initialize_duplicate(duplicator, other)
+    self.course = duplicator.options[:target_course]
```
Comment (kxmbrian) [inline app/models/course/video/tab.rb]: Could you add logic to check if any of the original tab's videos have been copied and associate them here?

This is particularly for object duplication. The idea is that it should not matter whether the video or its tab are duplicated first: as long as both are in the duplication list, their children should be associated. Specs for this can be added in `object_duplication_service_spec.rb`.

Comment (yichenshen) [reply app/models/course/video/tab.rb]: Alright, added the association and tests.

**Comment by kxmbrian** [comment]
Could you include selected tabs in the count of items to be duplicated in `ItemsSelectorMenu`?

Other than that, LGTM!

**Comment by kxmbrian** [comment]
@yichenshen we are merging this first. You can fix the item count in a separate PR.

**Comment by yichenshen** [comment]
Ah ok, will do. Sorry for the delay.

**Comment by yichenshen** [comment]
Fixed in ##2895
