### PR TITLE
Fix performance issue for course home page

### LINKED ISSUE #3643: Home page N+1
For large courses with a lot of todos, once user logs in, the home page shows all pending lesson plan items (mostly videos and assessments for a course like 1010s/x).

Page load on local is around 10-16s. On prod is around 6-10s.

N+1 from various partials contributed to this long TTFB. Below is a non-exhaustive list, more details to be furnished after further digging:
- [x] Course::LessonPlan::Todo item: :actable is not eagerloaded, resulting in N+1 when checking if user can attempt lesson plan item https://github.com/Coursemology/coursemology2/blob/023de7daf90932478b74678ff09aaa6dc75dcb23/app/controllers/course/courses_controller.rb#L50 This debt must be repaid.
- [x] Todo video button reuses video attempt button, which fires query to check if there's any video submission for current course user. There will never be any for videos marked as todo. Fixed in https://github.com/Coursemology/coursemology2/pull/3647
- [x] N+1 _personal_or_ref_time partial. Temp solution impemented to show a shortlist of latest todos only, so that impact of N+1 is not so severe on home page. #3655 

Query caching is also a possible contributor to increased memory usage on prod.

### PR DESCRIPTION
**Pull request by ekowidianto**
Closes #3643

### CODE REVIEW

File: app/controllers/course/courses_controller.rb [hunk 1]
```diff
@@ -47,8 +47,7 @@ def load_todos
     return unless current_course_user&.student?
 
     todos = Course::LessonPlan::Todo.pending_for(current_course_user).
-            includes(:user, item: :course).order(updated_at: :desc)
-    # TODO: Fix n+1 query for #can_user_start?
+            preload(:user, { item: [:course, actable: :conditions] }).order(updated_at: :desc)
     todos = todos.select(&:can_user_start?)
```
Comment (ekowidianto) [inline app/controllers/course/courses_controller.rb:51]: can_user_start? here calls the line below
https://github.com/Coursemology/coursemology2/blob/17bd932080e814a58ecfa50108b355d81d71e76c/app/models/concerns/course/lesson_plan/item_todo_concern.rb#L13

There are 3 types of actable for each actable here (which is why we preload actable):
1. Survey - allow_response_after_end and end_at are part of the survey model
https://github.com/Coursemology/coursemology2/blob/29e08a85b7f410f85fc6cce11722a1e2170802de/app/models/course/survey.rb#L34
2. Video - by default it is always true since can_user_start is not implemented in the video actable class
3. Assessment
https://github.com/Coursemology/coursemology2/blob/268b63fc98ccf65dd95aa5e3d292bfa79e21d8f3/app/models/concerns/course/assessment/todo_concern.rb#L7
The conditions_satisfied_by? below also calls conditions which is why we preload conditions after actable to prevent N+1
https://github.com/Coursemology/coursemology2/blob/e7880d7a08fd1b89ab3133b123bcc91d25866679/lib/extensions/conditional/active_record/base.rb#L60

**Review by zhuhanming — APPROVED** [review]
Thanks for clarifying! Looks good to me :)
