### PR TITLE
fix(questionFlags): Recreate questionFlags upon successful unsubmission

### LINKED ISSUE #3366: React error after creating programming queustio

### PR DESCRIPTION
**Pull request by ekowidianto**
closes #3366 

Refer to the issue above. When a question is created after there is an existing submission, there is no answer created to this question created for the submission. As a result, no questionFlags is created as well for this question. When an unsubmission happens, the answer to this question is then newly created. As a result, the questionFlags in the react reducer needs to be re-generated.

### CODE REVIEW

File: client/app/bundles/course/assessment/submission/reducers/questionsFlags.js [hunk 1]
```diff
@@ -71,6 +72,7 @@ export default function (state = {}, action) {
         },
       };
     }
+    case actions.UNSUBMIT_SUCCESS:
```
Comment (zhuhanming) [inline client/app/bundles/course/assessment/submission/reducers/questionsFlags.js:75]: This line is unreachable, because the same `case` is above. Can I check which one is the one you want?
