### PR TITLE
Fix bugs in SingleFileInput

### LINKED ISSUE #2682: Unpublishing an achivement breaks its badge
When an achievement is unpublished, the link to its image gets broken.

---

Quick investigation (by @weiqingtoh):

`SingleFileInput` has some issue when there is an existing badge - it registers 'Undefined' into the redux-form element. What happens is that this gets submitted as a string to the controller, which then results in some funny behaviour resulting in the badge being updated incorrectly.

### PR DESCRIPTION
**Pull request by weiqingtoh**
Fixes #2682. 

### The issue
When editing existing achievements, updating fields other than the badge caused  the badge to be lost. I've traced the cause to the image uploader. 

### The cause
There are a few states for the image uploader when no file is selected: `null` initially, and `undefined` when a file was selected, then cancelled. When the submit button is clicked, react (or redux-form) casts that into a string and sends that in as a param. 

When the rails controller receives it, it treats the string in an unexpected way, over-writing the previously stored image/badge, causing the issue above. 

### The Fix
There are two things in this PR to fix this: 
 - _Rails Controller_: Reject the params if a string (instead of a File) is provided. 
 - _SingleFileInput_: Standardise the state of the image uploader to an empty string (because of casting to a string, an empty string works better than `'null'` or `'undefined'`.

### Things to Do
When trying to solve this, I found a few other things to address: (Will open those as issues as this fix is more important)
 - Allow users to delete achievement badges
 - Reorganise `SingleFileInput` to adhere to the necessary react conventions (controlled inputs).

### CODE REVIEW

File: spec/controllers/course/achievement/achievements_controller_spec.rb [hunk 1]
```diff
@@ -93,5 +93,34 @@
...
+        end
+        subject { controller.send(:achievement_params)[:badge] }
+
+        context 'when the badge field is not an uploaded file' do
+          let(:badge_attribute) { 'null' }
+
+          it { is_expected.to be_nil }
+        end
+
+        context 'when the badge field is not an uploaded file' do
```
Comment (fonglh) [inline spec/controllers/course/achievement/achievements_controller_spec.rb]: This should be "... is ~not~ an uploaded file".
