### PR TITLE
Course duplication job

### LINKED ISSUE #2198: Duplication of full course should be run as a job
References #1705.

Long running duplications timeout and give the user the impression that the task has failed even though the duplication eventually finishes.

## Main Objectives

1. Duplication is already written as a service, but should be delegated to a job so the app server doesn't get blocked.

2. After starting duplication, show a flash message to the user that his course is being duplicated in the background and to check back later.

3. Send an email to the user when duplication is done.

### PR DESCRIPTION
**Pull request by jeremyyap**
Resolves #2198 

This PR will do the following:

- [x] Exclude survey objects from course duplication for now
- [x] Move course duplication into a job
- [x] Send email to notify user of job completion
- [x] Update course duplication UI to redirect to job path
- [x] Update and add course duplication specs

### CODE REVIEW

**Comment by jeremyyap** [comment]
Ready for review!

**Comment by fonglh** [comment]
Can we inform the user if duplication fails?

File: app/jobs/course/duplication_job.rb [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+  #
+  # @param [Course] current_course The course to duplicate.
+  # @param [User] current_user The user that initiated the duplication service.
+  # @param [Hash] duplication_params A hash of duplication parameters.
+  # @param [Array] all_objects All the objects in the course.
+  # @param [Array] selected_objects The objects to duplicate.
+  def perform_tracked(current_course, current_user, duplication_params = {},
+                      all_objects = [], selected_objects = [])
+    instance = Course.unscoped { current_course.instance }
+    ActsAsTenant.with_tenant(instance) do
```
Comment (allenwq) [inline app/jobs/course/duplication_job.rb]:
```
ActsAsTenant.without_tenant do
   xxx
end
```

Let's standardize and use without tenant.  There's no request in jobs, hence no tenant.

**Comment by allenwq** [comment]
LGTM, @fonglh ?   

Now if the job fails user will get an error but not through email.  
Ultimately I think we should show the progress of duplication, otherwise if the user waits too long, he/she will probably go and duplicate again, ends up multiple courses created.

File: lib/autoload/duplicator.rb [hunk 2]
```diff
@@ -36,7 +36,8 @@ def duplicate(stuff)
     duplicated_stuff = []
     stuff = [*stuff] unless stuff_is_enumerable
     stuff.each do |obj|
-      duplicated_stuff << duplicate_object(obj)
+      duplicated_object = duplicate_object(obj)
+      duplicated_stuff << duplicated_object unless duplicated_object.nil?
```
Comment (weiqingtoh) [inline lib/autoload/duplicator.rb]: @jeremyyap just a quick question, this was changed because it is possible for `duplicate_object(obj)` to return nil?

Comment (jeremyyap) [inline lib/autoload/duplicator.rb]: Yes

Comment (weiqingtoh) [inline lib/autoload/duplicator.rb]: Just checking, when does that happen?

**Comment by jeremyyap** [comment]
When there are objects excluded from duplication. This change was done so that surveys could be excluded. In the future this will apply to duplication cherrypicking as well.
