### PR TITLE
Fix inconsistent grade input behaviours on Safari and Chrome

### LINKED ISSUE #5111: Grade multiplier on mobile browser
On my mobile browser, I am unable to type in "." in the multiplier section for late submissions, however it is possible when typing from the laptop or pasting the value in of example "0.8"

5DDDBFEC-963F-4077-8BB4-AFE5AFF7AE83_1_201_a

Running Safari on IOS 16.0,

### PR DESCRIPTION
**Pull request by purfectliterature**
Closes #5111.

Since `type="number"` is removed from the input, the steps (numeric up/down buttons) are no longer available. To compensate, it was re-implemented that pressing the arrow up and down keys will still increase and decrease the grade by 1.

### CODE REVIEW

File: client/app/bundles/course/assessment/submission/containers/QuestionGrade.jsx [hunk 1]
```diff
@@ -7,25 +7,61 @@ import PropTypes from 'prop-types';
...
+ * Checks if the given value is a valid decimal of the form `0.00`.
+ *
+ * @param {string} value the string to be checked
+ * @returns `true` if `value` is a valid decimal
+ */
+const isValidDecimal = (value) => /^\d*(\.\d?)?$/.test(value);
+
 class VisibleQuestionGrade extends Component {
-  handleGradingField(value) {
+  handleFieldChange(value) {
```
Comment (ekowidianto) [inline client/app/bundles/course/assessment/submission/containers/QuestionGrade.jsx:27]: Do we need to have the return statements when `onChange` and `onBlur` are not expecting any return? Also, you might want to extract the common checks in both `handleFieldChange` and `handleFieldBlur`.

**Review by ekowidianto — COMMENTED** [review]
LGTM Thanks @purfectliterature ! Just a minor nit
