### PR TITLE
Fix cyclic validation for conditions with no dependent object.

### LINKED ISSUE #986: undefined method `specific_conditions' for nil:NilClass (NoMethodError)
```coursemology2/lib/autoload/course/conditional/user_satisfiability_graph.rb:62:in `reachable?': undefined method `specific_conditions' for nil:NilClass (NoMethodError)```

I get this error when migrating a course achievement. Inspected the source code, there is a validation which calls the following method:
```ruby
  def self.reachable?(source, dest)
    return true if source == dest

    dest.specific_conditions.index { |c| reachable?(source, c.dependent_object) }.present?
  end
```

In my case `dest` is an achievement which depends on a level, but level condition's `dependent_object` is always `nil` from our source: https://github.com/Coursemology/coursemology2/blob/master/app/models/course/condition/level.rb#L17
So `c.dependent_object` returns `nil` and then the exception raised.

@custode Is this a bug ?

### PR DESCRIPTION
**Pull request by custode**
Fix #986. This issue arise because level condition do not have any dependent conditional object.

Add the logic to handle the case in which destination may be nil.

### CODE REVIEW

**Comment by lowjoel** [comment]
@custode build failed

File: lib/autoload/course/conditional/user_satisfiability_graph.rb [hunk 1]
```diff
@@ -59,7 +59,7 @@ def evaluate(satisfied_conditions, course_user)
   def self.reachable?(source, dest)
     return true if source == dest
 
-    dest.specific_conditions.index { |c| reachable?(source, c.dependent_object) }.present?
+    dest.specific_conditions.index { |c| reachable?(source, c.dependent_object) }.present? if dest
```
Comment (lowjoel) [inline lib/autoload/course/conditional/user_satisfiability_graph.rb]: this would return nil. I suggest you explicitly return false unless dest at the start of the function

**Comment by custode** [comment]
@lowjoel fixed the issues
