### PR TITLE
Fixed broken 'More announcements' link

### LINKED ISSUE #248: Global announcements 'More announcements' link was broken
<code>No route matches [GET] "/announcements"</code>

### PR DESCRIPTION
**Pull request by dariusf**
Fixes #248

### CODE REVIEW

**Comment by lowjoel** [comment]
@dariusf please check the build status/lint errors before I review them, thanks.

File: app/controllers/announcements_controller.rb [hunk 1]
```diff
@@ -0,0 +1,10 @@
+class AnnouncementsController < ApplicationController
+
+  load_and_authorize_resource :announcement, through: :current_tenant, class:
+                                             Instance::Announcement.name
+  add_breadcrumb :index, :admin_announcements_path
```
Comment (lowjoel) [inline app/controllers/announcements_controller.rb]: Is this in admin?

File: app/controllers/announcements_controller.rb [hunk 2]
```diff
@@ -0,0 +1,10 @@
+class AnnouncementsController < ApplicationController
+
+  load_and_authorize_resource :announcement, through: :current_tenant, class:
```
Comment (lowjoel) [inline app/controllers/announcements_controller.rb]: ...What does this line do? Read the Cancancan documentation.

File: app/models/generic_announcement.rb [hunk 3]
```diff
@@ -0,0 +1,8 @@
+# Represents a generic announcement, which may be either a system-level or instance-level one.
+class GenericAnnouncement
+  include ActiveModel::Model
+
+  def self.all
+    SystemAnnouncement.all + Instance::Announcement.all
```
Comment (lowjoel) [inline app/models/generic_announcement.rb]: You might only want to define a method that returns only the active announcements. `all` can return quite a large number of records over time.

File: spec/features/generic_announcements_spec.rb [hunk 4]
```diff
@@ -0,0 +1,82 @@
+require 'rails_helper'
+
+RSpec.describe 'Generic announcements', type: :feature do
```
Comment (lowjoel) [inline spec/features/generic_announcements_spec.rb]: See #306 for the kind of feature specs... this builds on top of the fact that we want to structure our specs as user stories.

Comment (dariusf) [inline spec/features/generic_announcements_spec.rb]: On second thought this doesn't describe a workflow. It just tests that what is rendered in the view meets some criteria, given some data. Maybe I should make this a controller spec instead?

File: app/models/generic_announcement.rb [hunk 5]
```diff
@@ -0,0 +1,11 @@
+# Represents a generic announcement, which may be either a system-level or instance-level one.
+class GenericAnnouncement
+  include ActiveModel::Model
+
+  def self.valid
+    in_time_range = ['valid_from <= :now AND :now <= valid_to', {now: Time.zone.now}]
```
Comment (lowjoel) [inline app/models/generic_announcement.rb]: Use squeel -- I'm not sure if it can be composed but have a look.

File: app/views/announcements/edit.html.slim [hunk 6]
```diff
@@ -0,0 +1,3 @@
+h2
+  = t('.header')
+= render 'admin/announcements/form'
```
Comment (lowjoel) [inline app/views/announcements/edit.html.slim]: `render partial: 'form'`

File: app/views/announcements/index.html.slim [hunk 7]
```diff
@@ -0,0 +1,5 @@
+div.page-header
+  h1
+    = t('.header')
+= render partial: 'admin/announcements/announcement', collection: @announcements
```
Comment (lowjoel) [inline app/views/announcements/index.html.slim]: `render @announcements`, @allenwq keeps reminding me also >.<

Comment (dariusf) [inline app/views/announcements/index.html.slim]: This doesn't seem to work: `Missing partial system_announcements/_system_announcement`. Is it looking for the partial based on the types of the items in the collection?

File: app/controllers/announcements_controller.rb [hunk 8]
```diff
@@ -0,0 +1,7 @@
+class AnnouncementsController < ApplicationController
+  add_breadcrumb :index, :announcements_path
+
+  def index
+    @announcements = GenericAnnouncement.valid
```
Comment (dariusf) [inline app/controllers/announcements_controller.rb]: This line isn't covered by tests. Is there a need to cover it?

**Comment by lowjoel** [comment]
Please rebase against the latest master

File: app/controllers/announcements_controller.rb (hunk 8 above)
Comment (lowjoel) [inline app/controllers/announcements_controller.rb]: It should, unless your feature spec didn't trigger this action.

File: app/views/announcements/index.html.slim (hunk 7 above)
Comment (lowjoel) [inline app/views/announcements/index.html.slim]: Yes, it does. Okay, this works.

File: spec/features/generic_announcements_spec.rb [hunk 9]
```diff
@@ -0,0 +1,81 @@
...
+
+RSpec.feature 'Generic Announcements', type: :feature do
+  subject { page }
+  let(:instance) { create(:instance) }
+
+  with_tenant(:instance) do
+    let(:user) { create(:user) }
+
+    context 'As a User' do
+      before do
```
Comment (lowjoel) [inline spec/features/generic_announcements_spec.rb]: Single-use before blocks can be part of the scenario itself.

File: spec/features/generic_announcements_spec.rb [hunk 10]
```diff
@@ -0,0 +1,81 @@
...
+        visit announcements_path
+      end
+
+      scenario 'I should not see any announcements if there are none' do
+        it { is_expected.not_to have_selector('div.instance-announcement') }
+        it { is_expected.not_to have_selector('div.system-announcement') }
+      end
+    end
+
+    context 'As a User' do
```
Comment (lowjoel) [inline spec/features/generic_announcements_spec.rb]: Then merge contexts.

Comment (lowjoel) [inline spec/features/generic_announcements_spec.rb]: Or, if the same setup needs to be done, then let the context share the `before` block.

File: spec/features/generic_announcements_spec.rb [hunk 11]
```diff
@@ -0,0 +1,81 @@
...
+        end
+      end
+
+      before do
+        instance.announcements.clear
+        SystemAnnouncement.destroy_all
+        announcements.each(&:save!)
+      end
+
+      it 'I should see all both types of announcements in the same view' do
```
Comment (lowjoel) [inline spec/features/generic_announcements_spec.rb]: `scenario`

File: spec/models/generic_announcement_spec.rb [hunk 12]
```diff
@@ -0,0 +1,38 @@
+require 'rails_helper'
+
+RSpec.describe GenericAnnouncement, type: :model do
+  describe '.default_scope' do
```
Comment (lowjoel) [inline spec/models/generic_announcement_spec.rb]: You aren't really describing `.default_scope`, I'd just put this in the `describe` block.

Comment (lowjoel) [inline spec/models/generic_announcement_spec.rb]: wait, you're describing `.valid`.

File: spec/models/generic_announcement_spec.rb [hunk 13]
```diff
@@ -0,0 +1,38 @@
...
+      sorted_dates = system_dates.sort { |a, b| b <=> a }
+      expect(system_dates).to eq(sorted_dates)
+
+      instance_dates = instance.map(&:valid_from)
+      sorted_dates = instance_dates.sort { |a, b| b <=> a }
+      expect(instance_dates).to eq(sorted_dates)
+    end
+
+    it 'orders system announcements before instance announcements' do
+      announcements = GenericAnnouncement.valid
```
Comment (lowjoel) [inline spec/models/generic_announcement_spec.rb]: This can be more concise.

The rule in Ruby (and most functional languages) is to favour intent over implementation. You should be doing that..

I'm not sure what the exact method is, try googling around?

Comment (dariusf) [inline spec/models/generic_announcement_spec.rb]: I would personally use a method like `is_ordered_by` (with a hash param for ascending/descending), but there doesn't seem to be one provided by default. If I had to implement one, would it make sense to extend `Enumerable` with it? Or should I just implement it locally as a sort of helper function?

**Comment by dariusf** [comment]
Fixed all the problems with the tests; everything is covered now. The only issue left is the non-DRY way of checking if the lists are ordered by valid date.

File: app/models/generic_announcement.rb [hunk 14]
```diff
@@ -0,0 +1,13 @@
+# Represents a generic announcement, which may be either a system-level or instance-level one.
+class GenericAnnouncement
+  include ActiveModel::Model
+
+  # @return [Array<SystemAnnouncement|Instance::Announcement>]
+  def self.valid
+    now = Time.zone.now
+    in_time_range = proc { (valid_from <= now) & (valid_to >= now) }
+    system = SystemAnnouncement.includes(:creator).where(&in_time_range)
```
Comment (lowjoel) [inline app/models/generic_announcement.rb]: You're looking for `currently_valid`. This is an extension I defined in ActiveRecord::Base.

```ruby
system = SystemAnnouncement.includes(:creator).currently_valid
instance = ...
```

so maybe this method should be called currently_valid.

File: config/locales/en/announcements.yml [hunk 15]
```diff
@@ -0,0 +1,6 @@
+en:
+  announcements:
+    index:
+      header: 'All Announcements'
+    edit:
```
Comment (lowjoel) [inline config/locales/en/announcements.yml]: You don't have an 'edit' link?

File: spec/features/generic_announcements_spec.rb [hunk 16]
```diff
@@ -0,0 +1,48 @@
...
+        visit announcements_path
+        it { is_expected.to have_selector('div.system-announcement') }
+      end
+
+      scenario 'I should see both types of announcements in the same view' do
+        create_list(:system_announcement, 5, creator: user, updater: user)
+        create_list(:instance_announcement, 5, instance: instance, creator: user, updater: user)
+        visit announcements_path
+
+        5.times do |i|
```
Comment (lowjoel) [inline spec/features/generic_announcements_spec.rb]: you should iterate over the list of created announcements more than anything else.

The ID of the announcement div should be generated based on the database record ID, not the index of the page...

File: spec/models/generic_announcement_spec.rb [hunk 17]
```diff
@@ -0,0 +1,38 @@
+require 'rails_helper'
+
+RSpec.describe GenericAnnouncement, type: :model do
+  describe '.valid' do
+    before do
+      create_list(:system_announcement, 3)
```
Comment (lowjoel) [inline spec/models/generic_announcement_spec.rb]: `before...create` might be better written as `let!(:identifier) { ... }`. See http://betterspecs.org @allenwq

**Comment by dariusf** [comment]
Fixed all problems again. Test failure is due to #320 (happens in last commit).

File: app/models/generic_announcement.rb [hunk 18]
```diff
@@ -0,0 +1,11 @@
+# Represents a generic announcement, which may be either a system-level or instance-level one.
+class GenericAnnouncement
+  include ActiveModel::Model
+
+  # @return [Array<SystemAnnouncement|Instance::Announcement>]
```
Comment (lowjoel) [inline app/models/generic_announcement.rb]: Better documentation would be nice...

Comment (lowjoel) [inline app/models/generic_announcement.rb]: Ah, I guess this could do.

File: spec/models/generic_announcement_spec.rb [hunk 19]
```diff
@@ -0,0 +1,58 @@
...
+      system_sorted = system_a.map(&:valid_from).each_cons(2).all?(&desc_comparator)
+      instance_sorted = instance_a.map(&:valid_from).each_cons(2).all?(&desc_comparator)
+
+      expect(system_sorted).to be_truthy
+      expect(instance_sorted).to be_truthy
+    end
+
+    it 'orders system announcements before instance announcements' do
+      announcements = GenericAnnouncement.currently_valid
+      sorted_announcements = announcements.sort do |a, b|
```
Comment (lowjoel) [inline spec/models/generic_announcement_spec.rb]: how about `announcements.take_while { |a| a.is_a?(SystemAnnouncement) }` and assert that it matches?

Comment (lowjoel) [inline spec/models/generic_announcement_spec.rb]: or... reduce?

Comment (dariusf) [inline spec/models/generic_announcement_spec.rb]: `take_while`, then assert that the remaining `all? { |x| x.is_a?(Instance::Announcement) }`?

Comment (lowjoel) [inline spec/models/generic_announcement_spec.rb]: Yep, something to that effect. Sorting is overkill IMO
