### PR TITLE
Fix Comment Bugs

### LINKED ISSUE #1896: Comments Edit/Delete
The comments cannot be edited or deleted after creation, need to refresh the page

### PR DESCRIPTION
**Pull request by kxmbrian**
Fixes #1896 and #891 

- Newly-added comments could not be edited because the updated list of comments sent back by the server after comment creation was not enclosed in a `div_for(topic)`, so the topic_id was missing and the edit form failed to render.
- `parent` for new comments is assigned to be `posts.order_topologically.last`. Since comments are now linear, this is the last post in the chain.
- Combined some of the `js: true` specs.
- After assessment answer comments are deleted, the root (topmost) comment's toolbar was not shown. Have fixed that.
- Previously, replies in the comments center get the first post in the thread as their parent. This breaks the linearity and the posts are displayed as nested (see #1879).

### CODE REVIEW

**Comment by weiqingtoh** [comment]
Setting the parent_id in the backend assumes that every subsequent post reply references the last post?

**Comment by kxmbrian** [comment]
Yes, posts are re-parented upon deletion, if deletion is allowed.

File: app/controllers/course/discussion/posts_controller.rb [hunk 1]
```diff
@@ -7,6 +7,11 @@ class Course::Discussion::PostsController < Course::ComponentController
   include Course::Discussion::PostsConcern
 
   def create
+    # Set parent as the topologically last pre-existing post, if it exists.
+    # @post is in @topic.posts, so we filter out @post, which has no id yet.
+    if @topic.posts.length > 1
+      @post.parent = @topic.posts.ordered_topologically.flatten.select(&:id).last
```
Comment (allenwq) [inline app/controllers/course/discussion/posts_controller.rb]: `@topic.posts.ordered_topologically.flatten.select(&:id)` will this one always return nil ?  cause the new post is the last ?

Comment (kxmbrian) [inline app/controllers/course/discussion/posts_controller.rb]: `select(&:id)` will exclude it because `@post.id` is nil, so `last` will not return it

Comment (allenwq) [inline app/controllers/course/discussion/posts_controller.rb]: oh correct, don't now why I thought `select` is `map`, lol
