### PR TITLE
Re-evaluate the package when time/memory limit or language changes

### LINKED ISSUE #1204: Updating time/memory limits alone when package has failed to import does not work
## Steps to Reproduce
1. Set a low time and memory limit. e.g. 1 MB and 1 second
2. Upload a package. The error `The package could not be imported: the package exceeded the maximum time allowed by the question.` is shown.
3. Change the memory limit to 30 MB and click 'Update Programming'. The same error message is shown.

However, with the same limits of 30 MB and 1 second, when the same package file is selected for upload before clicking 'Update Programming', it is successfully imported.

### PR DESCRIPTION
**Pull request by allenwq**
Fix #1204 

Found this bug when doing the migration.

Basically, if the import job fails due to time/memory limit, increase the limit won't make it evaluate again.

This PR fixes the code to evaluate again if any of those fields changed. and does some minor refactoring in programming question spec.

### CODE REVIEW

File: app/models/course/assessment/question/programming.rb [hunk 1]
```diff
@@ -110,22 +110,40 @@ def non_autograded_template_files=(template_files)
 
   private
 
+  # Create new package or re-evaluate the old package.
+  def process_package
+    return if @duplicating
```
Comment (weiqingtoh) [inline app/models/course/assessment/question/programming.rb]: Shall we have `attr_reader :duplicating` and then do a `before_save :process_package, unless: :duplicating?`

File: app/models/course/assessment/question/programming.rb [hunk 2]
```diff
@@ -110,22 +110,40 @@ def non_autograded_template_files=(template_files)
...
+
+    if attachment_changed?
+      return remove_old_package if attachment.nil?
+      process_new_package
```
Comment (weiqingtoh) [inline app/models/course/assessment/question/programming.rb]: How about `attachment.nil? ? remove_old_package : process_new_package`?

File: app/models/course/assessment/question/programming.rb (hunk 1 above)
Comment (allenwq) [inline app/models/course/assessment/question/programming.rb]: attr_reader also defines a method `duplicating?` ?

File: app/models/course/assessment/question/programming.rb (hunk 2 above)
Comment (allenwq) [inline app/models/course/assessment/question/programming.rb]: 👍

File: app/models/course/assessment/question/programming.rb [hunk 3]
```diff
@@ -110,22 +110,40 @@ def non_autograded_template_files=(template_files)
...
+    elsif time_limit_changed? || memory_limit_changed? || language_id_changed?
+      # For non-autograded questions, the attachment is not present
+      evaluate_package if attachment
+    end
+  end
+
+  def evaluate_package
```
Comment (weiqingtoh) [inline app/models/course/assessment/question/programming.rb]: Should allow `process_new_package` to use `evaluate_package` also? Since there are some commonalities. The `execute_after_commit` is here for some reason also, because we don't want the job to start before the transaction is committed, so we can add that reasoning.

Comment (allenwq) [inline app/models/course/assessment/question/programming.rb]: I have thought about doing it that way, that they are a bit different, one of them handles the attachment.

File: app/models/course/assessment/question/programming.rb (hunk 1 above)
Comment (weiqingtoh) [inline app/models/course/assessment/question/programming.rb]: If I remember correctly, `attr_reader :duplicating` is the same as this:
```ruby
def duplicating
  @duplicating
end
```

**Comment by fonglh** [comment]
Does this fix #1204?

**Comment by allenwq** [comment]
@fonglh Oops, don't know there was already an issue, yes, it will fix 1204.

File: app/models/course/assessment/question/programming.rb (hunk 3 above)
Comment (weiqingtoh) [inline app/models/course/assessment/question/programming.rb]: Ok maybe we keep it separate. I think there is some context when delaying the update of the attachment also ><

Comment (allenwq) [inline app/models/course/assessment/question/programming.rb]: it delays only when the attachment changed, which is process new package.

File: app/models/course/assessment/question/programming.rb (hunk 2 above)
Comment (allenwq) [inline app/models/course/assessment/question/programming.rb]: Fixed ! This makes me think of Micheal Jackson :-P

File: app/models/course/assessment/question/programming.rb (hunk 1 above)
Comment (allenwq) [inline app/models/course/assessment/question/programming.rb]: I have defined a new `skip_process_package?` method instead, cause I need to override it in factories.

File: app/models/course/assessment/question/programming.rb [hunk 4]
```diff
@@ -151,4 +166,8 @@ def assign_test_case_attributes
   def clear_duplication_flag
     @duplicating = nil
   end
+
+  def skip_process_package?
+    !!@duplicating
```
Comment (allenwq) [inline app/models/course/assessment/question/programming.rb]: Discussed with @kxmbrian sometime ago that we should use it.

**Comment by allenwq** [comment]
@weiqingtoh updated.

File: app/models/course/assessment/question/programming.rb [hunk 5]
```diff
@@ -110,22 +110,37 @@ def non_autograded_template_files=(template_files)
 
   private
 
+  # Create new package or re-evaluate the old package.
+  def process_package
+    if attachment_changed?
+      attachment ? process_new_package : remove_old_package
+    elsif time_limit_changed? || memory_limit_changed? || language_id_changed?
```
Comment (weiqingtoh) [inline app/models/course/assessment/question/programming.rb]: @allenwq do we wanna support change in language id? I think you mean if python version change or?

Comment (allenwq) [inline app/models/course/assessment/question/programming.rb]: yes, here is the version change of a language. e.g. py3.5 => py3.6

Comment (weiqingtoh) [inline app/models/course/assessment/question/programming.rb]: Ok, so for now if someone changes it from say Python 3.5 to some other language (eg. Javascript), do we want the process_package to run?

Comment (allenwq) [inline app/models/course/assessment/question/programming.rb]: That's a good question 😄 

Now it will raise an `NotImplementedError` if we change the root language in UI ( I did some tests just now).  

If that part get implemented or fixed, I think it will go the first branch (`attachment_changed?`) if the root language version changed, because root language change means the deletion of old package and new package is generated.
