### PR TITLE
Modify activity feed page to skip deleted activity objects

### LINKED ISSUE #1115: Notifications Framework - Activity Feed for deleted Assessment
Steps to Reproduce:
1. Create assessment
2. Attempt assessment, triggering activity feed
3. Delete assessment
4. Go to landing page, error is triggered: `undefined method 'title' for nil:NilClass` for the following line:
`- assessment_link = link_to assessment.title, course_assessment_path(notification.course, assessment)`

### PR DESCRIPTION
**Pull request by weiqingtoh**
- Each activity may have 1 or more notifiers. Most notifiers are one-off and static (execpt activity feed).
- In the case of activity feed, underlying objects can be deleted, triggering errors when loading course homepage.
- Commit makes views to do a check before rendering the partials.

Fixes #1115.

### CODE REVIEW

**Comment by kxmbrian** [comment]
Looks okay to me 👍

**Comment by allenwq** [comment]
👍

File: app/controllers/course/courses_controller.rb [hunk 1]
```diff
@@ -8,7 +8,7 @@ def index # :nodoc:
 
   def show # :nodoc:
     @registration = Course::Registration.new
-    @activity_feeds = recent_activity_feeds.limit(20).includes(:activity)
+    @activity_feeds = recent_activity_feeds.limit(20).includes(activity: [:object, :actor])
```
Comment (lowjoel) [inline app/controllers/course/courses_controller.rb]: I think there should be a scope for "valid" or something like that.

Comment (weiqingtoh) [inline app/controllers/course/courses_controller.rb]: @lowjoel any thoughts on how to do it as a scope? I'm not sure how to do it because of polymorphism.

Comment (lowjoel) [inline app/controllers/course/courses_controller.rb]: oh, there's polymorphism, that'll hurt. can't do it then.

Comment (weiqingtoh) [inline app/controllers/course/courses_controller.rb]: Although the scope might be the best option, the issue with this implementation is that if the base object for the last 20 activities has been deleted, there wouldn't be an activity feed. That said, we don't expect that to happen a lot, so I guess this is a fair tradeoff.

Comment (lowjoel) [inline app/controllers/course/courses_controller.rb]: This is fine. More complex solution can come later.
