### PR TITLE
Fix deadlock

### LINKED ISSUE #1371: Fix deadlock
Rollbar issue 166
```PG::TRDeadlockDetected: ERROR: deadlock detected
DETAIL: Process 3919 waits for ShareLock on transaction 50799; blocked by process 3928.
Process 3928 waits for ShareLock on transaction 50798; blocked by process 3919.
HINT: See server log for query details.
CONTEXT: while updating tuple (1205,20) in relation "course_assessment_answers"```

Happens in `answer.auto_grade!` in concurrency environment.

This will also help with #1359

### PR DESCRIPTION
**Pull request by allenwq**
This will fix #1371 

When we save the auto grading ,there 3 duplicated queries for updating the timestamp of discussion_topics, it will cause a deadlock in some concurrency cases, similar to: http://elioxman.blogspot.sg/2013/02/postgres-deadlock.html

Also there are **13 queries** generated when we save the auto grading because of the validation and updating of answer... this could cause performance issues because answers grading runs quite frequently.  Changed to directly update the column and skipped the validation of answer, we should not update or validate the answer in this case, because answer is not changed at all.

@fonglh You can rebase #1323 after this, should be no more failures when run 2 processes in same container, I have verified in #1359

### CODE REVIEW

**Comment by fonglh** [comment]
Is the test failure random?

```
1) Course::Assessment::Submission with tenant :instance #unsubmit! when the submission is submitted sets all latest answers in the submission to attempting
     Failure/Error: expect(subject.latest_answers.all?(&:attempting?)).to be(true)
     
       expected true
            got false
     # ./spec/models/course/assessment/submission_spec.rb:333:in `block (5 levels) in <top (required)>'
     # ./spec/support/bullet.rb:7:in `block in extended'
```

**Comment by allenwq** [comment]
@fonglh It's random, but I still need to find why, it could be messed up by the jobs.

**Comment by allenwq** [comment]
@fonglh Yes, because of the job, still need to wait, updated.

File: lib/extensions/discussion_topic/active_record/base.rb [hunk 1]
```diff
@@ -5,11 +5,15 @@ module ClassMethods
...
-    def acts_as_discussion_topic(display_globally: false)
+    # @option options [Boolean] :touch Set to true if the topic need to be touched upon updating.
+    def acts_as_discussion_topic(display_globally: false, touch: false)
       acts_as :discussion_topic, class_name: Course::Discussion::Topic.name
       # For autoload to work correctly after class changed, we store the model name first and
       # constantize later.
       Course::Discussion::Topic.global_topic_model_names << name if display_globally
+
+      # This can be removed after https://github.com/hzamani/active_record-acts_as/pull/78
+      define_method(:touch_actable) {} unless touch
```
Comment (fonglh) [inline lib/extensions/discussion_topic/active_record/base.rb]: What does this do?

Comment (allenwq) [inline lib/extensions/discussion_topic/active_record/base.rb]: This updates the timestamp of the actable class, don't need that for topics.  You can check the details from link above.
