### PR TITLE
Fix race condition which results in unsynced submission and answer states

### LINKED ISSUE #2046: Answer states inconsistent with submissions
In some race conditions, answer states get inconsistent with submissions. ( e.g. a graded submission could have an attempting answer ).

This could result in autograded submissions cannot be graded.

### PR DESCRIPTION
**Pull request by weiqingtoh**
Fixes #2046 - please read that PR for more of the investigation. 

Problem: There are instances of submitted submissions with answers that are still in an attempting state.
Investigation into this surfaced a race condition - given that user has 2 tabs open, the user can send 2 requests to the coursemology server: (i) Finalise submission, (ii) Submit and evaluat the answer for the current programming question being worked on.

The race condition occurs because (ii) would recreate an attempting answer after autograding is done, but is unaware that the submission could be finalised during this process. This would result in (i) having a SubJobError where the job is unable to cope with the IllegalStateError raised.

The desync in states results in the course_staff being unable to grade the answers, requring some intervention.

Solution: Two fixes are done to ensure the following -
1. Answers are not created for reattempting if the submission is submitted
2. Submissions would auto-grade all answers, including those in attempting state (which could have been created after finalising the submission, but before the autograding job has run)

The solutions proposed greatly reduces the possibility of the race condition happening, but there is a very minute possibility (in a perfect world with 0 latency) that the race condition can still occur. Hence, the submission autograding job is implemented with retries to try to catch such cases.

### CODE REVIEW

File: app/services/course/assessment/submission/auto_grading_service.rb [hunk 1]
```diff
@@ -38,6 +50,13 @@ def grade_answers(submission)
   def grade_answer(answer)
     raise ArgumentError if answer.changed?
     answer.auto_grade!
+    # Catch errors if answer is in attempting state, caused by a race condition where
+    # a new attempting answer is created while the submission is finalised, but before the
+    # autograding job is executed.
+  rescue IllegalStateError
```
Comment (fonglh) [inline app/services/course/assessment/submission/auto_grading_service.rb]: https://github.com/Coursemology/coursemology2/pull/1934 allows graded and evaluated answers to be evaluated again.

For consistency, would it be better to allow attempting answers to be evaluated too? Then there's no need to specially catch an `IllegalStateError`.

I think it'll be clearer to explicitly allow it in the Answer model's state transition definition. That'll also keep the state transition logic in 1 place and prevent unexpected surprises. (The next person might use this elsewhere wonder why grading `attempting` answers doesn't throw an exception like the model definition suggests.)

File: app/services/course/assessment/submission/auto_grading_service.rb [hunk 2]
```diff
@@ -25,9 +29,17 @@ def grade(submission)
...
+  #
+  # Retries are implemented in the case where a race condition occurs, ie. when a new
+  # attempting answer is created after the submission is finalised, but before the
+  # autograding job is run for the submission.
   def grade_answers(submission)
-    jobs = submission.latest_answers.map { |answer| grade_answer(answer) }
-    wait_for_jobs(jobs)
+    tries = 0
+    while tries <= MAX_AUTOGRADE_RETRIES && submission.reload.latest_answers.reject(&:graded?).any?
+      jobs = submission.latest_answers.map { |answer| grade_answer(answer) }
```
Comment (allenwq) [inline app/services/course/assessment/submission/auto_grading_service.rb]: we only need to grade "that" answer

File: app/services/course/assessment/submission/auto_grading_service.rb (hunk 1 above)
Comment (weiqingtoh) [inline app/services/course/assessment/submission/auto_grading_service.rb]: > For consistency, would it be better to allow attempting answers to be evaluated too? 

Would advise against this, as there are use cases where the `IllegalStateError` is valid. From a business logic sense it would be better for us to disallow this by default in the code, and specially `rescue` it if need be, so that new developers won't accidentally call `#auto_grade!` on `attempting` answers.

> I think it'll be clearer to explicitly allow it in the Answer model's state transition definition. That'll also keep the state transition logic in 1 place and prevent unexpected surprises. (The next person might use this elsewhere and wonder why grading `attempting` answers doesn't throw an exception like the model definition suggests.)

If the intent is on better readability and trying to figure things out, I disagree also because this fix was tailored to resolve the race condition introduced in this AutoGradingService. In case of future refactoring/changes, I would expect that the developer does a `git blame`, reads the commit message, reads the PR, and reads the issue before deciding on what to modify. I've specially added a lot more information/context into these areas as well. 


Any thoughts @allenwq ?

Comment (fonglh) [inline app/services/course/assessment/submission/auto_grading_service.rb]: The intent is to reduce the number of special scenarios. If every `auto_grade!` on an `attempting` answer is going to be specially rescued and forced to `submitted`, then it might as well be valid to `auto_grade!` an `attempting` answer.

Is there anywhere that needs `auto_grade!` to fail on an `attempting` answer?

Comment (weiqingtoh) [inline app/services/course/assessment/submission/auto_grading_service.rb]: > Is there anywhere that needs `auto_grade!` to fail on an `attempting` answer?

Imo, in every other case except this one because of a race condition, because that aligns with the business logic. Currently `auto_grade!` is only being used in 1 other place, which is when a single answer is submitted to be evaluated. In that case, I would prefer to have the `IllegalStateError` as there are cases where we need to limit the number of attempts. 

Other future use cases would come in once we have discussed multiple submissions and reattempting, so in cases where an exception needs to be made, I'd rather have the dev doing an explicit `rescue`

Comment (allenwq) [inline app/services/course/assessment/submission/auto_grading_service.rb]: > so that new developers won't accidentally call #auto_grade! on attempting answers.
Agree with this, actually even ourselves might manually call `auto_grade!` to fix some db issues sometimes, it's better to raise an error if the answer is not in the correct state and `submitted_at` is not present.

It doesn't make sense to let `auto_grade` set the `submitted_at`, or we should add a new method.

File: app/services/course/assessment/submission/auto_grading_service.rb [hunk 3]
```diff
@@ -25,10 +29,22 @@ def grade(submission)
...
+  # autograding job is run for the submission.
   def grade_answers(submission)
-    jobs = submission.latest_answers.map { |answer| grade_answer(answer) }
-    wait_for_jobs(jobs)
-    aggregate_failures(jobs.map { |job| job.job.reload })
+    jobs_by_qn = submission.latest_answers.map { |a| [a.question_id, grade_answer(a)] }.to_h
+    wait_for_jobs(jobs_by_qn.values)
+
+    tries = 0
+    while submission.reload.latest_answers.reject(&:graded?).any? && tries <= MAX_RETRIES
```
Comment (allenwq) [inline app/services/course/assessment/submission/auto_grading_service.rb]: Just realized there are evaluated answers, should reject them as well. Or filter answers by attempting and submitted state.

**Comment by allenwq** [comment]
LGTM, @fonglh  ?

File: app/services/course/assessment/submission/auto_grading_service.rb (hunk 1 above)
Comment (fonglh) [inline app/services/course/assessment/submission/auto_grading_service.rb]: Ok I forgot there's a `submitted_at`. Also spoke with @weiqingtoh and I'm ok with keeping this approach. We might have to relook all the state transitions when multiple submissions is implemented.
