### PR TITLE
Fix user time_zone for invalid and nil time_zones

### LINKED ISSUE #1215: Handle exceptions when user's timezone is removed from global timezone list
Regarding https://github.com/Coursemology/coursemology2/pull/1173#discussion_r72899744

### PR DESCRIPTION
**Pull request by weiqingtoh**
This PR fixes an issue where users who did not set a time-zone will see GMT time in emailers instead of the Application Default (SGP).

Commit Details:
- Also fixes #1215 where timezones might be removed from ActiveSupport::TimeZone, rendering persisted time_zones unusable.
- Shift validation into private method, to validate that user's time_zone can be nil or some valid value.
- If persisted time_zone is invalid or nil, return application default timezone, otherwise, return that timezone.

### CODE REVIEW

File: app/models/user.rb [hunk 1]
```diff
@@ -110,4 +125,13 @@ def default_email_record
     result ||= valid_emails.first
     result
   end
+
+  # Custom time_zone validation as +#time_zone+ getter has been modified.
+  #
+  # Possible time_zones include +nil+ or those listed in ActiveSupport::TimeZone
+  def validate_time_zone
+    return if self[:time_zone].nil? || ActiveSupport::TimeZone.all.map(&:name).include?(self[:time_zone])
```
Comment (kxmbrian) [inline app/models/user.rb]: For this and `#time_zone`, is it better to do `ActiveSupport::TimeZone[self[:time_zone]].present?` ?

Comment (weiqingtoh) [reply app/models/user.rb]: Definitely cleaner. Fixed and thanks!
