### PR TITLE
Ignore duplicate emails for course invitations

### LINKED ISSUE #3249: Course Invitation CSV silently failing when there are duplicates
#2432 seems to address this but the problem is still there.

The test case for duplicates that was added [here](https://github.com/Coursemology/coursemology2/commit/667cfd24fc) was before #2432 was opened.

`validate_new_invitation_emails` in `process_invitation_concern.rb` adds the error to the duplicates but no filtering is done before saving, so a rollback occurs and other invites fail too.

`invalid_course_user_errors` and `invalid_invitation_email_errors` in `Course::UserInvitationController` do not catch the duplicates because they are valid instances.

From #2432:

> Invite all non-duplicated students in the CSV file
> Ignore duplicated students

### To replicate:

Import CSV:
```
name,email,role
Foo,bar@foo.com,student
Bar,bar@foo.com,teaching_assistant
Bar,bar3@foo.com,teaching_assistant
```
### Expected: 
warning and invitation of non-dups

### What is happening:
There is no messages to indicate the error, and invitation is not created for the non-duplicates.

### Solution

1. Filter the duplicates before saving to prevent a rollback and the non-dups not saving 
2. Implement warning for when invitations succeed.

OR

The invitation can continue to fail with duplicates but show an error message.

### PR DESCRIPTION
**Pull request by fonglh**
Fixes merge conflicts in #3257 introduced by #3261.

Send one invite for duplicated emails in the invitation CSV. Show the number of duplicates in the CSV.

Fixes #3249.

### CODE REVIEW

File: app/services/course/user_invitation_service.rb [hunk 1]
```diff
@@ -23,24 +23,26 @@ def initialize(current_user, current_course)
...
+      new_course_users, existing_course_users, duplicate_users = invite_users(users)
       raise ActiveRecord::Rollback unless new_invitations.all?(&:save)
       raise ActiveRecord::Rollback unless new_course_users.all?(&:save)
       true
     end
 
     send_registered_emails(new_course_users) if success
     send_invitation_emails(new_invitations) if success
-    success ? [new_invitations, existing_invitations, new_course_users, existing_course_users].map(&:size) : nil
+    success ? [new_invitations, existing_invitations, new_course_users, existing_course_users, duplicate_users].map(&:size) : nil
```
[the remark this answers is not in the document]
Comment (fonglh) [reply app/services/course/user_invitation_service.rb]: anything else is just as unwieldy

**Comment by fonglh** [comment]
Current behaviour totally ignores duplicates within the CSV file. Ideally, it should send one invitation even if the email appears multiple times in the CSV file.

**Comment by fonglh** [comment]
Sample CSV file:

```
Heuristic Gates,heuristic_gates@hotmail.com
Vigorous Fermi,vigorous_fermi@gmail.com
Vigorous Fermi,vigorous_fermi@gmail.com
Vigorous Fermi,vigorous_fermi@gmail.com
Relaxed Mahavira,relaxed_mahavira@gmail.com
Relaxed Mahavira,relaxed_mahavira@gmail.com
Relaxed Mahavira,relaxed_mahavira@gmail.com
```

When invited by file, the success message is `Successfully invited users from the uploaded file: 3 new invitations sent, 0 already invited, 0 users just enrolled, 0 already enrolled.`

The warning message is `4 duplicate emails ignored.`

**Comment by dexterleng** [comment]
I've made changes but I'm not sure how to push them here:

https://github.com/dexterleng/coursemology2/commit/c610e8efb1b4cb97f2ed93434f348f4cbe14be7e

**Comment by fonglh** [comment]
Thanks I've incorporated your fixes.

**Comment by trangmei** [comment]
If the csv contains, among other entries,
```
Vigorous Fermi,vigorous_fermi@gmail.com
Vigorous Fermi,vigorous_fermi@gmail.com,student,y
```
there's a silent rollback because they're recognised as different users

File: app/services/course/user_invitation_service.rb [hunk 2]
```diff
@@ -63,13 +65,25 @@ def resend_invitation(invitations)
...
+  #     Array<Hash>,
   #   ]
   #   A tuple containing the users newly invited, already invited,
-  #     newly registered and already registered respectively.
+  #     newly registered and already registered, and duplicate users respectively.
   # @raise [CSV::MalformedCSVError] When the file provided is invalid.
   def invite_users(users)
-    users = parse_invitations(users)
-    process_invitations(users)
+    users, duplicate_users = parse_invitations(users)
```
Comment (jeremyyap) [inline app/services/course/user_invitation_service.rb]: Instead of manipulating the non-unique users here, how about partitioning differently in `#parse_invitations`:

```ruby
users.partition.with_index do |user, index|
  users.find_index( { |u| u.email == user.email } == index
end
```

Alternative:
```ruby
unique_users = users.uniq(&:email)
unique_users, users - unique_users
```

File: app/services/concerns/course/user_invitation_service/parse_invitation_concern.rb [hunk 3]
```diff
@@ -29,7 +33,9 @@ def parse_invitations(users)
       else
         parse_from_form(users)
       end
-    result.each { |user| user[:email] = user[:email].downcase }
+    users = result.each { |user| user[:email] = user[:email].downcase }
+    emails = users.map { |user| user[:email] }
+    users.partition { |user| emails.count(user[:email]) == 1 }
```
Comment (louietyj) [inline app/services/concerns/course/user_invitation_service/parse_invitation_concern.rb]: This is an O(n^2) operation which could be done in O(n) using a simple hashset (granted, the csv is probably small).

File: app/services/course/user_invitation_service.rb [hunk 4]
```diff
@@ -63,13 +65,25 @@ def resend_invitation(invitations)
...
+
+    # Process the duplicate users once instead of totally ignoring them.
+    unique_duplicates = duplicate_users.uniq { |user| user[:email] }
+    users += unique_duplicates
+    # Remove one of each duplicate user from the duplicate_users array so the
+    # count in the warning message will be correct.
+    unique_duplicates.each do |user|
+      index = duplicate_users.index(user)
+      duplicate_users.delete_at(index) if index
+    end
```
Comment (louietyj) [inline app/services/course/user_invitation_service.rb]: This logic is unnecessarily awkward. Instead, in the case of duplicates you could let parse_invitations put the first duplicate instance into the success pile and the rest into the skipped pile.

**Comment by dexterleng** [comment]
I can't push here so heres the code:

https://github.com/dexterleng/coursemology2/commit/d50cf8a03a69a279deb7a689d8a39c2ac5873a62

It uses the logic brought up by @louietyj.

**Comment by louietyj** [comment]
@dexterleng https://ruby-doc.org/stdlib-2.6/libdoc/set/rdoc/Set.html

File: app/services/course/user_invitation_service.rb (hunk 2 above)
Comment (fonglh) [reply app/services/course/user_invitation_service.rb]: `users - unique_users` actually results in an empty array as all occurrences of each entry in `unique_users` is removed.
